export const title = 'Uptick Talent Map';

export const startupInput = [
  {
    id: 1,
    label: 'First Name',
    type: 'text',
    required: true,
    name: 'firstName',
    placeHolder: 'First name',
  },
  {
    id: 2,
    label: 'Last Name',
    type: 'text',
    required: true,
    name: 'lastName',
    placeHolder: 'Last name',
  },
  {
    id: 3,
    label: 'Email',
    type: 'email',
    required: true,
    name: 'email',
    placeHolder: 'Email address',
  },
  {
    id: 4,
    label: 'Phone Number',
    type: 'tel',
    required: true,
    name: 'phone',
    placeHolder: '+2348010101010',
  },
  {
    id: 5,
    label: 'Name of Company',
    type: 'text',
    required: true,
    name: 'nameOfCompany',
    placeHolder: 'eg.Google',
  },
  {
    id: 6,
    label: 'Upload Company Logo',
    type: 'file',
    required: true,
    name: 'companyLogo',
  },
  {
    id: 7,
    label: 'Country',
    type: 'text',
    required: true,
    name: 'country',
    placeHolder: 'eg.Nigeria',
  },
  {
    id: 8,
    label: 'City',
    type: 'text',
    required: true,
    name: 'city',
    placeHolder: 'eg.Jos, Plateau',
  },
  {
    id: 9,
    label: 'What tech talent role are you looking to fill?',
    type: 'select',
    options: [
      'Frontend Software Engineer',
      'Backend Software Engineer',
      'Fullstack Software Engineer',
      'Product Designer',
      'Product Researcher',
      'Product Manager',
      'Data Scientist',
      'Mobile Engineer',
      'QA Test Engineer',
      'Product Owner',
      'Business Development Manager',
      'Other...',
    ],
    required: true,
    name: 'talentRole',
    placeHolder: '',
  },
  {
    id: 10,
    label: 'What level of expertise do you wish to fill for these roles',
    type: 'select',
    options: [
      'Entry-level',
      'Mid-level',
      'Senior level',
      'Manager Level or C-suite for a startup',
      'Other...',
    ],
    required: true,
    name: 'level',
    placeHolder: '',
  },
  {
    id: 11,
    label: 'Salary Range for Positions',
    type: 'select',
    options: [
      'N100k - 250k',
      'N250k - 400K',
      'N400k - 500K',
      'N500k - 1m',
      'N1m - 1.5m',
      'Other...',
    ],
    required: true,
    name: 'level',
    placeHolder: '',
  },
  {
    id: 12,
    label: 'How do you hear about us?',
    type: 'select',
    options: [
      'Friends and Families',
      'LinkedIn',
      'Twitter',
      'Instagram',
      'Facebook',
      'Tech Communities',
      'Other...',
    ],
    required: true,
    name: 'how',
    placeHolder: 'Nil',
  },
  {
    id: 11,
    label: 'How do you hear about us?',
    type: 'select',
    options: [
      'Friends and Families',
      'LinkedIn',
      'Twitter',
      'Instagram',
      'Facebook',
      'Tech Communities',
      'Other...',
    ],
    required: true,
    name: 'how',
    placeHolder: 'Nil',
  },
];
