import type { Metadata } from 'next';
import { Inter, Poppins, Cabin } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

const poppins = Poppins({ weight: ['400', '500', '600'], subsets: ['latin'] });
const cabin = Cabin({ weight: ['400', '500', '600'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Uptick Talent Website',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${poppins.className} ${cabin.className}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
