#!/bin/sh

# Change the working directory to the "dev" directory
cd "$(dirname -- "$0")/../dev"

echo '🏗️👷 Running checks on your code before committing' 🔍🧐

# Check Prettier standards
npm run check-format || {
    echo '🤢🤮🤢🤮 Its so ugly!! - Your styling looks disgusting. 🤢🤮🤢🤮
        Prettier Check Failed. Run npm run format, add changes and try commit again.';
    exit 1  # Exit the script with an error code
}

echo '🏗️👷 checking for eslint errors' 🔍🧐

# Check ESLint Standards
npm run check-lint || {
    echo '😤🏀👋😤 Get that beans code out of here! 😤🏀👋😤 
        ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.';
    exit 1  # Exit the script with an error code
}

echo '🏗️👷 checking for typescript errors' 🔍🧐

# Check tsconfig standards
npm run check-types || {
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
        Are you seriously trying to write that? Make the changes required above.';
    exit 1  # Exit the script with an error code
}

echo '🏗️👷 Running tests' 🔍🧐

# Run tests
npm run testing || {
    echo '❌ Tests failed. Make sure all your tests pass before committing.';
    exit 1  # Exit the script with an error code
}

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'

echo '✅✅ Awesome work! ✅✅'
echo '🚀⛅ Run git push to upload your changes to the remote repository ⛅🚀'

# Change the working directory back to the original directory (optional)
cd -

# Change the working directory to the "admin" directory
cd "$(dirname -- "$0")/../admin"

echo '🏗️👷 Running checks on your code before committing' 🔍🧐

# Check Prettier standards
npm run check-format || {
    echo '🤢🤮🤢🤮 Its so ugly!! - Your styling looks disgusting. 🤢🤮🤢🤮
        Prettier Check Failed. Run npm run format, add changes and try commit again.';
    exit 1  # Exit the script with an error code
}

echo '🏗️👷 checking for eslint errors' 🔍🧐

# Check ESLint Standards
npm run check-lint || {
    echo '😤🏀👋😤 Get that beans code out of here! 😤🏀👋😤 
        ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.';
    exit 1  # Exit the script with an error code
}

echo '🏗️👷 checking for typescript errors' 🔍🧐

# Check tsconfig standards
npm run check-types || {
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
        Are you seriously trying to write that? Make the changes required above.';
    exit 1  # Exit the script with an error code
}

echo '🏗️👷 Running tests' 🔍🧐

# Run tests
npm run testing || {
    echo '❌ Tests failed. Make sure all your tests pass before committing.';
    exit 1  # Exit the script with an error code
}

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'

echo '✅✅ Awesome work! ✅✅'
echo '🚀⛅ Run git push to upload your changes to the remote repository ⛅🚀'

# Change the working directory back to the original directory (optional)
cd -